const    WWDGT_IRQn: u32                   = 0;      // window watchDog timer interrupt
const    LVD_IRQn: u32                     = 1;      // LVD through EXTI line detect interrupt                   
const    TAMPER_IRQn: u32                  = 2;      // tamper through EXTI line detect                          
const    RTC_IRQn: u32                     = 3;      // RTC through EXTI line interrupt                          
const    FMC_IRQn: u32                     = 4;      // FMC interrupt                                            
const    RCU_CTC_IRQn: u32                 = 5;      // RCU and CTC interrupt                                    
const    EXTI0_IRQn: u32                   = 6;      // EXTI line 0 interrupt                                    
const    EXTI1_IRQn: u32                   = 7;      // EXTI line 1 interrupt                                    
const    EXTI2_IRQn: u32                   = 8;      // EXTI line 2 interrupt                                    
const    EXTI3_IRQn: u32                   = 9;      // EXTI line 3 interrupt                                    
const    EXTI4_IRQn: u32                   = 10;     // EXTI line 4 interrupt                                    
const    DMA0_Channel0_IRQn: u32           = 11;     // DMA0 channel0 interrupt                                  
const    DMA0_Channel1_IRQn: u32           = 12;     // DMA0 channel1 interrupt                                  
const    DMA0_Channel2_IRQn: u32           = 13;     // DMA0 channel2 interrupt                                  
const    DMA0_Channel3_IRQn: u32           = 14;     // DMA0 channel3 interrupt                                  
const    DMA0_Channel4_IRQn: u32           = 15;     // DMA0 channel4 interrupt                                  
const    DMA0_Channel5_IRQn: u32           = 16;     // DMA0 channel5 interrupt                                  
const    DMA0_Channel6_IRQn: u32           = 17;     // DMA0 channel6 interrupt                                  
const    ADC0_1_IRQn: u32                  = 18;     // ADC0 and ADC1 interrupt                                  
const    USBD_HP_CAN0_TX_IRQn: u32         = 19;     // CAN0 TX interrupts
const    USBD_LP_CAN0_RX0_IRQn: u32        = 20;     // CAN0 RX0 interrupts                                      
const    CAN0_RX1_IRQn: u32                = 21;     // CAN0 RX1 interrupt                                       
const    CAN0_EWMC_IRQn: u32               = 22;     // CAN0 EWMC interrupt                                      
const    EXTI5_9_IRQn: u32                 = 23;     // EXTI[9:5] interrupts                                     
const    TIMER0_BRK_IRQn: u32              = 24;     // TIMER0 break interrupt                                   
const    TIMER0_UP_IRQn: u32               = 25;     // TIMER0 update interrupt                                  
const    TIMER0_TRG_CMT_IRQn: u32          = 26;     // TIMER0 trigger and commutation interrupt                 
const    TIMER0_Channel_IRQn: u32          = 27;     // TIMER0 channel capture compare interrupt                 
const    TIMER1_IRQn: u32                  = 28;     // TIMER1 interrupt                                         
const    TIMER2_IRQn: u32                  = 29;     // TIMER2 interrupt                                         
const    TIMER3_IRQn: u32                  = 30;     // TIMER3 interrupt                                         
const    I2C0_EV_IRQn: u32                 = 31;     // I2C0 event interrupt                                     
const    I2C0_ER_IRQn: u32                 = 32;     // I2C0 error interrupt                                     
const    I2C1_EV_IRQn: u32                 = 33;     // I2C1 event interrupt                                     
const    I2C1_ER_IRQn: u32                 = 34;     // I2C1 error interrupt                                     
const    SPI0_IRQn: u32                    = 35;     // SPI0 interrupt                                           
const    SPI1_IRQn: u32                    = 36;     // SPI1 interrupt                                           
const    USART0_IRQn: u32                  = 37;     // USART0 interrupt                                         
const    USART1_IRQn: u32                  = 38;     // USART1 interrupt                                         
const    USART2_IRQn: u32                  = 39;     // USART2 interrupt                                         
const    EXTI10_15_IRQn: u32               = 40;     // EXTI[15:10] interrupts                                   
const    RTC_Alarm_IRQn: u32               = 41;     // RTC alarm interrupt                                      
const    USBD_WKUP_IRQn: u32               = 42;     // USBD Wakeup interrupt                                    
const    TIMER7_BRK_IRQn: u32              = 43;     // TIMER7 break interrupt                                   
const    TIMER7_UP_IRQn: u32               = 44;     // TIMER7 update interrupt                                  
const    TIMER7_TRG_CMT_IRQn: u32          = 45;     // TIMER7 trigger and commutation interrupt                 
const    TIMER7_Channel_IRQn: u32          = 46;     // TIMER7 channel capture compare interrupt                 
const    ADC2_IRQn: u32                    = 47;     // ADC2 global interrupt                                    
const    EXMC_IRQn: u32                    = 48;     // EXMC global interrupt                                    
const    SDIO_IRQn: u32                    = 49;     // SDIO global interrupt                                    
const    TIMER4_IRQn: u32                  = 50;     // TIMER4 global interrupt                                  
const    SPI2_IRQn: u32                    = 51;     // SPI2 global interrupt                                    
const    UART3_IRQn: u32                   = 52;     // UART3 global interrupt                                   
const    UART4_IRQn: u32                   = 53;     // UART4 global interrupt                                   
const    TIMER5_IRQn: u32                  = 54;     // TIMER5 global interrupt                                  
const    TIMER6_IRQn: u32                  = 55;     // TIMER6 global interrupt                                  
const    DMA1_Channel0_IRQn: u32           = 56;     // DMA1 channel0 global interrupt                           
const    DMA1_Channel1_IRQn: u32           = 57;     // DMA1 channel1 global interrupt                           
const    DMA1_Channel2_IRQn: u32           = 58;     // DMA1 channel2 global interrupt                           
const    DMA1_Channel3_Channel4_IRQn: u32  = 59;     // DMA1 channel3 and channel4 global Interrupt              
const    DMA1_Channel4_IRQn: u32           = 60;     // DMA1 channel3 global interrupt
const    ENET_IRQn: u32                    = 61;     // ENET global interrupt                                    
const    ENET_WKUP_IRQn: u32               = 62;     // ENET Wakeup interrupt                                    
const    CAN1_TX_IRQn: u32                 = 63;     // CAN1 TX interrupt                                        
const    CAN1_RX0_IRQn: u32                = 64;     // CAN1 RX0 interrupt                                       
const    CAN1_RX1_IRQn: u32                = 65;     // CAN1 RX1 interrupt                                       
const    CAN1_EWMC_IRQn: u32               = 66;     // CAN1 EWMC interrupt                                      
const    USBFS_IRQn: u32                   = 67;     // USBFS global interrupt

